blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
import api

# mobile API
from rest_framework import routers
router = routers.DefaultRouter()
router.register('entries', api.NewsAPIView, 'entries')
router.register('categories', api.BlogCategoryAPIViewSet, 'categories')
router.register('hotbox', api.HotNewsBox, 'hotbox')

urlpatterns = patterns('',
    # url(r'^$', NewsListView.as_view(), name='index'),
    # url(r'^(?P<slug>[\w-]+)/update/', NewsUpdateView.as_view(), name='update'),
    # url(r'^(?P<slug>[\w-]+)', NewsDetailView.as_view(), name='details'),
    # url(r'^create', NewsCreateView.as_view(), name='new'),
    # url(r'^category/(?P<slug>[\w-]+)', CategoryDetailView.as_view(), name='category'),
    # url(r'categories/create', CategoryCreateView.as_view(), name='newcategory'),
    # url(r'categories/', CategoryListView.as_view(), name='categories'),
)

organizations/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
    url(r'^invitations/', views.UserInvitations.as_view(), name="invitations"),
    url(r'^accept/(?P<key>[\w-]+)/', views.InviteAcceptView.as_view(), name="accept"),
    url(r'^create/', views.OrganizationCreateView.as_view(), name="create"),
    url(r'^(?P<slug>[\w-]+)/background/', views.NGOBackgroundView.as_view(), name="background"),
    url(r'^(?P<slug>[\w-]+)/news/create/', views.NGONewsCreate.as_view(), name="news-create"),
    url(r'^(?P<slug>[\w-]+)/news/(?P<news_slug>[\w-]+)/', views.NGONewsDetail.as_view(), name="news-detail"),
    url(r'^(?P<slug>[\w-]+)/news/', views.NGONewsList.as_view(), name="news-list"),
    url(r'^(?P<slug>[\w-]+)/projects/add/', views.NGOProjectAdd.as_view(), name="project-add"),
    url(r'^(?P<slug>[\w-]+)/projects/', views.NGOProjectList.as_view(), name="project-list"),
    url(r'^(?P<slug>[\w-]+)/invite/', views.InviteUsers.as_view(), name="invite"),
    url(r'^(?P<slug>[\w-]+)/update/', views.OrganizationUpdateView.as_view(), name="update"),
    url(r'^(?P<slug>[\w-]+)/members/', views.OrganizationMemberList.as_view(), name="members"),
    url(r'^(?P<slug>[\w-]+)/member-delete/', views.OrganizationMemberDelete.as_view(), name="member-delete"),
    url(r'^(?P<slug>[\w-]+)/locations/', views.OrganizationLocationList.as_view(), name="locations"),
    url(r'^(?P<slug>[\w-]+)/location-add/', views.OrganizationLocationAdd.as_view(), name="location-add"),
    url(r'^(?P<slug>[\w-]+)/location-delete/', views.OrganizationLocationDelete.as_view(), name="location-delete"),
    url(r'^(?P<slug>[\w-]+)/about/', views.OrganizationView.as_view(template_name='organizations/organization_info.html'), name="info"),
    url(r'^(?P<slug>[\w-]+)/', views.OrganizationView.as_view(), name="detail"),
    url(r'^', views.OrganizationListView.as_view(), name="index"),
)

places/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from articles.views import TopLevelArticleView
from locations.views import (CityRankingView, CountryRankingView,
                             LocationRankingView, RegionRankingView)
from staticpages.views import PageView, HomeView
from userspace.views import RegisterFormView, UserActivityView
from places_core.views import FileServeView
admin.autodiscover()

from civmail.admin import civmail_admin_site
from places_core import actstreams

# djangorestframework
from rest_framework import routers
from rest import views
router = routers.DefaultRouter()

handler500 = 'places_core.views.handler500'

# Api Views
#router.register(r'news_add', views.SimpleNewsViewSet, base_name="news_add")
router.register(r'current_user', views.CurrentUserViewSet, base_name='current_user')

# Site Views
router.register(r'users', views.UserViewSet)
router.register(r'categories', views.CategoryViewSet)
router.register(r'comments', views.CommentsViewSet, base_name=r'comment')
router.register(r'votes', views.CommentVoteViewSet, base_name=r'vote')
router.register(r'tags', views.TagViewSet, base_name=r'tag')
router.register(r'news', views.NewsViewSet, base_name=r'news')
router.register(r'discussion', views.ForumCategoryViewSet, base_name=r'discussion')
router.register(r'topics', views.ForumViewSet, base_name=r'topics')
router.register(r'replies', views.DiscussionRepliesViewSet, base_name=r'replies')
router.register(r'reports', views.AbuseReportViewSet, base_name=r'reports')
router.register(r'idea_categories', views.IdeaCategoryViewSet, base_name=r'idea_categories')
router.register(r'badges', views.BadgeViewSet, base_name=r'badges')
router.register(r'galleries', views.GalleryViewSet, base_name=r'galleries')
router.register(r'ideas', views.IdeaListViewSet, base_name=r'ideas')
router.register(r'idea_votes', views.IdeaVoteCounterViewSet, base_name=r'idea_votes')
router.register(r'usermedia', views.MediaViewSet, base_name=r'usermedia')
router.register(r'my_actions', views.UserActionsRestViewSet, base_name=r'my_actions')
router.register(r'polls', views.PollListViewSet, base_name=r'polls')
router.register(r'locationlist', views.LocationBasicViewSet, base_name=r'locationlist')
# django sitemaps framework
import places_core.sitemaps as sitemaps
sitemaps = {
    'locations': sitemaps.LocationSitemap,
    'ideas'    : sitemaps.IdeaSitemap,
    'news'     : sitemaps.NewsSitemap,
    'polls'    : sitemaps.PollsSitemap,
    'discussions': sitemaps.DiscussionSitemap,
    'projects': sitemaps.ProjectsSitemap,
    'articles': sitemaps.ArticleSitemap,
    'documents': sitemaps.EtherpadSitemap,
    'organizations': sitemaps.OrganizationSitemap,
    'guides': sitemaps.GuideSitemap,
}
# Javascript translations catalog
js_info_dict = {'packages': ('places_core', ), }

# Django Rest Framework
# ------------------------------------------------------------------------------
from locations.urls import router as location_router
from ideas.urls import router as idea_router
from topics.urls import router as discussion_router
from blog.urls import router as blog_router
from maps.urls import router as map_router
from userspace.urls import router as user_router
from places_core.urls import router as core_router
from gallery.urls import router as gallery_router
from notifications.urls import router as notification_router
from activities.urls import router as activity_router
from hitcounter.urls import router as hitcounter_router
from comments.urls import router as comment_router
from polls.urls import router as poll_router
from blessings.urls import router as bless_router
from projects.urls import router as project_router
from mapvotes.urls import router as mapvotes_router
urlpatterns = patterns('',
    url(r'^api-ideas/', include(idea_router.urls)),
    url(r'^api-locations/', include(location_router.urls)),
    url(r'^api-discussions/', include(discussion_router.urls)),
    url(r'^api-blog/', include(blog_router.urls)),
    url(r'^api-maps/', include(map_router.urls)),
    url(r'^api-userspace/', include(user_router.urls)),
    url(r'^api-core/', include(core_router.urls)),
    url(r'^api-gallery/', include(gallery_router.urls)),
    url(r'^api-notifications/', include(notification_router.urls)),
    url(r'^api-activities/', include(activity_router.urls)),
    url(r'^api-hitcounter/', include(hitcounter_router.urls)),
    url(r'^api-comments/', include(comment_router.urls)),
    url(r'^api-polls/', include(poll_router.urls)),
    url(r'^api-bless/', include(bless_router.urls)),
    url(r'^api-projects/', include(project_router.urls)),
    url(r'^api-mapvotes/', include(mapvotes_router.urls)),
)

from civmail.views import ContactEmailView, InviteFriendsView
urlpatterns += patterns('',
    url(r'^contact/', ContactEmailView.as_view(), name="contact"),
    url(r'^invite-friends/', InviteFriendsView.as_view(), name="invite_friends"),
)

from places_core.views import set_language
urlpatterns += patterns('',
    url(r'^', include('hitcounter.urls')),
    url(r'^ranking/(?P<code>[a-zA-Z]{2})/regions/', RegionRankingView.as_view(), name="ranking-regions"),
    url(r'^ranking/(?P<code>[a-zA-Z]{2})/locations/', LocationRankingView.as_view(), name="ranking-locations"),
    url(r'^ranking/(?P<code>[a-zA-Z]{2})/', CityRankingView.as_view(), name="ranking-cities"),
    url(r'^ranking/', CountryRankingView.as_view(), name="ranking-countries"),
    url(r'^activities/', include('activities.urls', namespace="activities")),
    url(r'^tracker/', include('user_tracker.urls', namespace="tracker")),
    url(r'^guides/', include('guides.urls', namespace="guides")),
    url(r'^organizations/', include('organizations.urls', namespace="organizations")),
    url(r'^simpleblog/', include('simpleblog.urls', namespace="simpleblog")),
    # user account
    url(r'^user/', include('userspace.urls', namespace='user')),
    url(r'^users/', include('userspace.urls', namespace='user')),
    url(r'^bookmarks/', include('bookmarks.urls')),
    # Email app
    url(r'^civmail/', include('civmail.urls', namespace='civmail')),
    url(r'^civmail-admin/', include(civmail_admin_site.urls)),
    # Maps
    url(r'^maps/', include('maps.urls', namespace='maps')),
    # blog
    url(r'^news/', include('blog.urls', namespace='blog')),
    # ideas
    url(r'^ideas/', include('ideas.urls', namespace='ideas')),
    # django-activity-stream
    url(r'^activity/', UserActivityView.as_view()),
    # social auth
    url('', include('social.apps.django_app.urls', namespace='social')),
    # django-discussions (e.g. user messages)
    # disabled because of lack South integrity
    #url('^messages/', include('discussions.urls', namespace='messages')),
    # Basic project views - the rest is within locations
    url('^projects/', include('projects.urls', namespace='projects')),
    # Discussions (e.g. forum)
    url('^discussion/', include('topics.urls', namespace='discussion')),
    # comments
    url('^comments/', include('comments.urls', namespace='comments')),
    # admin panel
    url(r'^fuck-off-i-am-awesome/', include(admin.site.urls)),
    # Abuse reports (static)
    url(r'^report/', include('places_core.urls', namespace='reports')),
    # User media
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    # Polls app
    url(r'^polls/', include('polls.urls', namespace='polls')),
    # Static pages
    url(r'^pages/', include('staticpages.urls', namespace='pages')),
    # media
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    # REST server
    url(r'^rest/', include(router.urls, namespace='rest')),
    # Haystack - search engine
    url(r'^search/', include('haystack.urls', namespace='search')),
    # django-messages: messages between users
    url(r'^messages/', include('postman.urls')),
    # Language support
    url(r'^i18n/setlang', set_language, name='set_language'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    # For robots - indexers :)
    url(r'^robots.txt$', FileServeView.as_view(filename='robots.txt')),
    # Captcha
    url(r'^captcha/', include('captcha.urls')),
    # Static Pages
    # Definition of static pages go here, you can add new ones by
    # copy-paste method.
    url(r'^home/', PageView.as_view(page='home')),
    url(r'^home-b/', PageView.as_view(page='home-b')),
    url(r'^home-c/', PageView.as_view(page='home-c')),
    url(r'^home-d/', PageView.as_view(page='home-d')),
    url(r'^home-e/', PageView.as_view(page='home-e')),
    url(r'^home-f/', PageView.as_view(page='home-f')),
    url(r'^home-g/', PageView.as_view(page='home-g')),
    url(r'^home-h/', PageView.as_view(page='home-h')),
    url(r'^home-i/', PageView.as_view(page='home-i')),
    url(r'^home-j/', PageView.as_view(page='home-j')),

    #url(r'^about/', PageView.as_view(page='about')),
    #url(r'^privacy/', PageView.as_view(page='privacy')),
    #url(r'^terms/', PageView.as_view(page='terms')),
    #url(r'^cookies/', PageView.as_view(page='cookies')),
    #url(r'^contact/', PageView.as_view(page='contact')),
    #url(r'^jobs/', PageView.as_view(page='jobs')),
    #url(r'^press/', PageView.as_view(page='press')),
    #url(r'^mission/', PageView.as_view(page='mission')),
    #url(r'^team/', PageView.as_view(page='team')),
    #url(r'^values/', PageView.as_view(page='values')),
    #url(r'^creed/', PageView.as_view(page='creed')),
    #url(r'^support/', PageView.as_view(page='support')),
    url(r'^feature/', PageView.as_view(page='feature')),

    # Etherpad - live collaboration tool
    url(r'^', include('etherpad.urls')),

    # Notifications for users - mainly views for testing.
    url(r'^', include('notifications.urls')),

    #url(r'^$', HomeView.as_view(template_name='staticpages/pages/home-e.html')),
    url(r'^$', RegisterFormView.as_view()),

polls/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from rest.routers import HybridRouter

import api
from .views import *

router = HybridRouter()
router.add_api_view('answers', url(r'^answers/', api.AnswerSetAPIView.as_view(), name='answers'))
router.add_api_view('timeline', url(r'^timeline/', api.AnswersInTimeAPIView.as_view(), name='timeline'))

urlpatterns = patterns('',
    url(r'^delete/(?P<pk>\d+)', delete_poll, name='delete'),
    url(r'^details/(?P<pk>\d+)', PollDetails.as_view(), name='details'),
    url(r'^results/(?P<pk>\d+)', PollResults.as_view(), name='results'),
    url(r'^verify/(?P<pk>\d+)', save_answers, name='verify'),
    url(r'(?P<location_slug>[\w-]+)/(?P<pk>\d+)/update/', PollUpdateView.as_view(), name='update'),
    url(r'(?P<slug>[\w-]+)/', SimplePollTakeView.as_view(), name='test'),
)

organizations/templates/organizations/index.html
{% extends 'places_core/base.html' %}{% load i18n actstream_tags %}
{% block title %}{{ organization }} - Civilhub.org {% endblock %}
{% block header %}<style type="text/css">
.user-logo {
  background-image: url({{ organization.background_url }});
}
@media
(-webkit-min-device-pixel-ratio: 2),
(min-resolution: 192dpi) {
  .user-logo {
    background-image: url({{ organization.retina_background_url }});
  }
}
.ngo-bg-logo {
  background-image: url({{ organization.logo.url }});
}
</style>
<div class="user-logo">
  <div class="container">
    <div class="ngo-info">
      <div class="ngo-bg-logo display-ib-m"><!-- <img src="{{ organization.logo.url }}" alt="{{ organization }}" class="ngo-logo-img"/> --></div>
      <div class="ngo-more-info">
        <div class="heading">{{ organization.category }}</div>
        <div class="name"><h1>{{ organization }}</h1></div>
        {% follow_button organization %}
      </div>
    </div>
    {% if access %}<div class="group-change-bg-btn"><a class="change-background-btn" href="{% url 'organizations:background' organization.slug %}">{% trans "Change background image" %}</a>
    <a href="{% url 'organizations:update' organization.slug %}" class="change-background-btn">{% trans "Update" %}</a></div>{% endif %}
  </div>
</div>
<nav id="filter-navbar" class="navbar navbar-default mt0" role="navigation" itemscope>
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-location-collapse-menu">
        <span class="sr-only">{% trans "Toggle navigation" %}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="row collapse navbar-collapse" id="bs-location-collapse-menu">
      <ul class="nav navbar-nav navbar-nav-userspace">
        <li><a href="{% url 'organizations:detail' organization.slug %}" itemprop="url"><span itemprop="name">{% trans "Summary" %}</span></a></li>
        <li><a href="{% url 'organizations:news-list' organization.slug %}" itemprop="url"><span itemprop="name">{% trans "News" %}</span></a></li>
        <li><a href="{% url 'organizations:info' organization.slug %}" itemprop="url"><span itemprop="name">{% trans "About Us" %}</span></a></li>
        <li><a href="{% url 'organizations:members' organization.slug %}" itemprop="url"><span itemprop="name">{% trans "Members" %}</span></a></li>
        <li><a href="{% url 'organizations:locations' organization.slug %}" itemprop="url"><span itemprop="name">{% trans "Locations" %}</span></a></li>
        <li><a href="{% url 'organizations:project-list' organization.slug %}" itemprop="url"><span itemprop="name">{% trans "Projects" %}</span></a></li>
      </ul>
    </div>
  </div>
</nav>{% endblock %}

organizations/templates/organizations/invitation_list.html
{% extends 'places_core/base.html' %}{% load i18n %}
{% block content %}<div class="main-content create-form newFormCreate"><h3>{% trans "invitations"|capfirst %}</h3>
<ul class="custom-tablelike list-unstyled mb0">{% for invitation in object_list %}
  <li class="custom-list-entry">{{ invitation }}<a href="{% url 'organizations:accept' invitation.key %}" class="text-green pull-right"><strong>{% trans "accept"|capfirst %}</strong></a></li>
{% endfor %}</ul></div>{% endblock %}

organizations/templates/organizations/location_add.html
{% extends 'organizations/index.html' %}{% load i18n staticfiles civil_tags %}
{% block require_scripts %}<script src="{% static 'places_core' %}/js/{% js_path %}/organizations-location-add.js"></script>{% endblock %}
{% block content %}<div class="main-content create-form newFormCreate"><h3>{% trans "Add more locations" %}</h3>
<form action="" method="post">{% csrf_token %}
  {{ form.as_p }}
  <div class="form-group mb0 top15">
    <button type="submit" class="btn btn-greenBig">{% trans "Save" %}</button>
  </div>
</form></div>{% endblock %}

organizations/templates/organizations/location_list.html
{% extends 'organizations/index.html' %}{% load i18n actstream_tags %}
{% block content %}
<div class="n-top-heading-spage">
  <h1>{% trans "Locations" %}</h1>
  <h2>{% trans "Place where we operate" %}</h2>
</div>
{% if access %}<p class="text-center"><a href="{% url 'organizations:location-add' object.slug %}"><strong>{% trans "Add more locations" %}</strong></a></p>{% endif %}
{% for location in object_list %}
  {% if forloop.counter0 == 0 or forloop.counter0|divisibleby:4 %}<div class="row">{% endif %}
  <div class="col-sm-3">
    <div class="n-sublocation" style="background-image: url({{ location.background_url }});">
      <div class="n-sublocation-content">
        <div class="n-sublocation-box">
        <a href="{{ location.get_absolute_url }}" class="name">{{ location }}</a>
          {% follow_button location %}
          </div>
      </div>
    </div>
    {% if access %}<form class="custom-inline-form" action="{% url 'organizations:location-delete' object.slug %}" method="post">{% csrf_token %}
    <input type="hidden" name="location_id" value="{{ location.pk }}">
    <button type="submit" class="text-danger">{% trans "Delete" %}</button>
    </form>{% endif %}
  </div>
  {% if forloop.counter|divisibleby:4 or forloop.counter == location.count %}</div>{% endif %}
{% endfor %}
{% include 'places_core/pagination.html' %}{% endblock %}


organizations/templates/organizations/member_list.html
{% extends 'organizations/index.html' %}{% load i18n %}
{% block content %}<div class="followers-entry">
  <h1>{% trans "Members" %}</h1>
  <h2>{% trans "People cooperate in this organization" %}</h2>
  {% if access %}<p class="text-center top15"><a href="{% url 'organizations:invite' organization.slug %}"><strong>{% trans "Invite more users" %}</strong></a></p>{% endif %}
  <div class="row">
    {% for member in object_list %}<div class="col-md-2 col-sm-4 col-xs-6">
      <div class="follower">
        <div class="follower-header">
          <a href="{{ member.profile.get_absolute_url }}">
            <div class="follower-background"><img src="{{ member.profile.thumb_url }}" alt="{{ member.get_full_name }}" /></div>
            <div class="follower-photo"><img src="{{ member.profile.avatar.url }}" alt="{{ member.get_full_name }}"></div>
          </a>
        </div>
        <div class="follower-info">
          <p class="follower-name">
            <a href="{{ member.profile.get_absolute_url }}">{{ member.get_full_name }}</a>
          </p>
          <div class="points"><span class="points-count">{{ member.profile.rank_pts }}</span> {% trans "pts" %}</div>
        </div>
      </div>
      {% if access %}<form class="custom-inline-form" action="{% url 'organizations:member-delete' organization.slug %}" method="post">{% csrf_token %}
      <input type="hidden" name="user_id" value="{{ member.pk }}">
      <div class="form-group text-center mb0">
        <button type="submit" class="text-danger">{% trans "Delete member" %}</button>
      </div>
      </form>{% endif %}
    </div>{% endfor %}
  </div>
</div>{% include 'places_core/pagination.html' %}{% endblock %}

organizations/templates/organizations/news_detail.html
{% extends 'organizations/index.html' %}{% load i18n comment_tags civil_tags staticfiles %}
{% block title %} {{ news }} - Civilhub.org {% endblock %}
{% block require_scripts %}<script src="{% static 'places_core/js' %}/{% js_path %}/organization-blog.js"></script>{% endblock %}
{% block description %}<meta name="description" content="{{ news.content|striptags|slice:":153"}}..." />{% endblock %}
{% block meta %}<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="CivilHub">
<meta name="twitter:title" content="{{ news }}">
<meta property="og:title" content="{{ news }}"/>
<meta property="og:image" content="https://civilhub.org{{ news.image.url }}"/>
<meta property="og:site_name" content="CivilHub"/>
<meta property="og:url" content="https://civilhub.org{{ news.get_absolute_url }}" />
<meta property="og:description" content="{{ news.content|striptags|slice:":153" }}..."/>
<meta property="article:author" content="https://civilhub.org{{ news.author.profile.get_absolute_url }}" />
<meta name="keywords" content="{{ news }}">
{% for tag in news.tags.all %}<meta property="article:tag" content="{{ tag }}">{% endfor %}
<meta property="article:published_time" content="{{ news.date_created|date:"c" }}">
{% if news.date_edited %}<meta property="article:modified_time" content="{{ news.date_edited|date:"c" }}">{% endif %}{% endblock %}
{% block content %}<div class="col-sm-9 main-content">
  <div class="blog-detail">
    <div class="row">
        <div class="col-sm-2">
          <div class="entry-avatar-col">
            <img src="{{ news.author.profile.avatar.url }}" alt="{{ news.author.get_full_name }}" class="user-avatar user-window-toggle" data-target="{{ news.author.pk }}" />
            <br />{{ news.author.profile.rank_pts }}
            {% include 'locations/share_buttons.html' %}
          </div>
        </div>
      <div class="col-sm-10">
        <div class="row news-header">
          <div class="col-sm-11">
            <h1>{{ news }}</h1>
            <small>
              {% trans "Created" %} {{ news.date_created | date:"j F Y" }} {% trans "by" %} <a href="{{ news.author.profile.get_absolute_url }}" class="blogNameCreator"><span class="user-window-toggle" data-target="{{ news.author.pk }}">{{ news.author.get_full_name }}</span></a></p>
            </small>
          </div>
          <div class="col-sm-1">{% if user.is_authenticated %}<h1><span class="submenu-toggle"></span></h1>{% endif %}
            <div class="entry-submenu">
              <ul>
                {% if user == news.author %}
                <li><a href="{% url 'simpleblog:update' news.slug  %}">{% trans "Edit" %}</a></li>
                {% endif %}
                {% if user.is_superuser or is_moderator %}
                <li><a href="{% url 'simpleblog:delete' news.slug %}">{% trans "Delete" %}</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
        {% if not news.has_default_image %}<img src="{{ news.image_url }}" alt="{{ news }}">{% endif %}
        <div class="row">
          <div class="acticle-content news-contetn mt25">{{ news.content|safe }}</div>
        </div>
        <div class="row">{% commentarea news %}</div>
      </div><!--colsm10-->
    </div>
  </div>
</div> <!-- colsm9-->
<div class="col-sm-3">
  <div class="ac-right-site">
    <div class="ac-small-box sm-box-invite mt0">
      <a href="/invite-friends/" class="full-click-box"></a>
      <div class="text-box">
        <h3>{% trans "Invite a firend" %}</h3>
        <p>{%trans "Your friends don’t know about CivilHub yet? Send them an invite!" %}</p>
      </div>
    </div>
  </div>
</div><!--colsm3-->{% endblock %}

organizations/templates/organizations/news_form.html
{% extends 'organizations/index.html' %}{% load i18n %}
{% block content %}<div class="col-sm-9">
  <div class="main-content create-form newFormCreate"><h3>{% trans "Create news" %} {% trans "in" %} {{ organization }}</h3>
    <form action="{% url 'simpleblog:create' %}" method="post" enctype="multipart/form-data" class="form-horizontal">{% csrf_token %}
      <div class="form-group">
        <label class="control-label col-sm-2">
          <label for="id_image">{% trans "Image" %}:</label>
        </label>
        <div class="col-sm-10">{{ form.image }}</div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <label for="id_name">{% trans "Name" %}:</label>
        </div>
        <div class="col-sm-10">{{ form.name }}</div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <label for="id_content">{% trans "Content" %}:</label>
        </div>
        <div class="col-sm-10">{{ form.content }}</div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <label for="id_category">{% trans "Category" %}:</label>
        </div>
        <div class="col-sm-10">{{ form.category }}</div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <label for="id_tags">{% trans "Tags" %}:</label>
        </div>
        <div class="col-sm-10">{{ form.tags }}</div>
      </div>
      {{ form.content_type }}
      {{ form.object_id }}
      <div class="form-group mb0">
        <div class="col-sm-2"></div>
        <div class="col-sm-10 text-right">
          <button type="submit" class="btn btn-greenBig">{% trans "Save" %}</button>
        </div>
      </div>
    </form>
  </div>
</div>
<div class="col-sm-3">
  <div class="sidebar">
    <div class="sidebar-label">{% trans "Help" %}</div>
    <ul class="sidebar-content custom-sidebar-nav">
        <li></li>
    </ul>
  </div>
</div>{% endblock %}

organizations/templates/organizations/organization_news_form.html
{% extends 'organizations/index.html' %}{% load i18n %}
{% block content %}<form action="{% url 'simpleblog:create' %}" method="post">{% csrf_token %}
  {{ form.as_p }}
  <button type="submit">{% trans "Save" %}</button>
</form>{% endblock %}

organizations/templates/organizations/socialproject_form.html
{% extends 'organizations/index.html' %}{% load i18n %}
{% block content %}<form method="post" action="">{% csrf_token %}
  {{ form.as_p }}
  <button type="submit">{% trans "Save" %}</button>
</form>{% endblock %}