blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
import api

# mobile API
from rest_framework import routers
router = routers.DefaultRouter()
router.register('entries', api.NewsAPIView, 'entries')
router.register('categories', api.BlogCategoryAPIViewSet, 'categories')
router.register('hotbox', api.HotNewsBox, 'hotbox')

urlpatterns = patterns('',
    # url(r'^$', NewsListView.as_view(), name='index'),
    # url(r'^(?P<slug>[\w-]+)/update/', NewsUpdateView.as_view(), name='update'),
    # url(r'^(?P<slug>[\w-]+)', NewsDetailView.as_view(), name='details'),
    # url(r'^create', NewsCreateView.as_view(), name='new'),
    # url(r'^category/(?P<slug>[\w-]+)', CategoryDetailView.as_view(), name='category'),
    # url(r'categories/create', CategoryCreateView.as_view(), name='newcategory'),
    # url(r'categories/', CategoryListView.as_view(), name='categories'),
)

maps/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

import api
import views

# REST API
from rest.routers import HybridRouter
router = HybridRouter()
router.register('pointers', views.MapPointerAPIViewSet, 'pointers')
router.register('objects', views.MapObjectAPIViewSet, 'objects')
router.add_api_view('data', url(r'^data/$', views.MapDataViewSet.as_view(), name='data'))
router.add_api_view('mapinput', url(r'^mapinput/$', views.MapinputAPI.as_view(), name='mapinput'))
router.add_api_view('new-markers', url(r'^new-markers/', api.MapObjectViewSet.as_view(), name='new-markers'))


urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^info/(?P<ct>\d+)/(?P<pk>\d+)/', views.IndexView.as_view(), name='info'),
)

places/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from articles.views import TopLevelArticleView
from locations.views import (CityRankingView, CountryRankingView,
                             LocationRankingView, RegionRankingView)
from staticpages.views import PageView, HomeView
from userspace.views import RegisterFormView, UserActivityView
from places_core.views import FileServeView
admin.autodiscover()

from civmail.admin import civmail_admin_site
from places_core import actstreams

# djangorestframework
from rest_framework import routers
from rest import views
router = routers.DefaultRouter()

handler500 = 'places_core.views.handler500'

# Api Views
#router.register(r'news_add', views.SimpleNewsViewSet, base_name="news_add")
router.register(r'current_user', views.CurrentUserViewSet, base_name='current_user')

# Site Views
router.register(r'users', views.UserViewSet)
router.register(r'categories', views.CategoryViewSet)
router.register(r'comments', views.CommentsViewSet, base_name=r'comment')
router.register(r'votes', views.CommentVoteViewSet, base_name=r'vote')
router.register(r'tags', views.TagViewSet, base_name=r'tag')
router.register(r'news', views.NewsViewSet, base_name=r'news')
router.register(r'discussion', views.ForumCategoryViewSet, base_name=r'discussion')
router.register(r'topics', views.ForumViewSet, base_name=r'topics')
router.register(r'replies', views.DiscussionRepliesViewSet, base_name=r'replies')
router.register(r'reports', views.AbuseReportViewSet, base_name=r'reports')
router.register(r'idea_categories', views.IdeaCategoryViewSet, base_name=r'idea_categories')
router.register(r'badges', views.BadgeViewSet, base_name=r'badges')
router.register(r'galleries', views.GalleryViewSet, base_name=r'galleries')
router.register(r'ideas', views.IdeaListViewSet, base_name=r'ideas')
router.register(r'idea_votes', views.IdeaVoteCounterViewSet, base_name=r'idea_votes')
router.register(r'usermedia', views.MediaViewSet, base_name=r'usermedia')
router.register(r'my_actions', views.UserActionsRestViewSet, base_name=r'my_actions')
router.register(r'polls', views.PollListViewSet, base_name=r'polls')
router.register(r'locationlist', views.LocationBasicViewSet, base_name=r'locationlist')
# django sitemaps framework
import places_core.sitemaps as sitemaps
sitemaps = {
    'locations': sitemaps.LocationSitemap,
    'ideas'    : sitemaps.IdeaSitemap,
    'news'     : sitemaps.NewsSitemap,
    'polls'    : sitemaps.PollsSitemap,
    'discussions': sitemaps.DiscussionSitemap,
    'projects': sitemaps.ProjectsSitemap,
    'articles': sitemaps.ArticleSitemap,
    'documents': sitemaps.EtherpadSitemap,
    'organizations': sitemaps.OrganizationSitemap,
    'guides': sitemaps.GuideSitemap,
}
# Javascript translations catalog
js_info_dict = {'packages': ('places_core', ), }

# Django Rest Framework
# ------------------------------------------------------------------------------
from locations.urls import router as location_router
from ideas.urls import router as idea_router
from topics.urls import router as discussion_router
from blog.urls import router as blog_router
from maps.urls import router as map_router
from userspace.urls import router as user_router
from places_core.urls import router as core_router
from gallery.urls import router as gallery_router
from notifications.urls import router as notification_router
from activities.urls import router as activity_router
from hitcounter.urls import router as hitcounter_router
from comments.urls import router as comment_router
from polls.urls import router as poll_router
from blessings.urls import router as bless_router
from projects.urls import router as project_router
from mapvotes.urls import router as mapvotes_router
urlpatterns = patterns('',
    url(r'^api-ideas/', include(idea_router.urls)),
    url(r'^api-locations/', include(location_router.urls)),
    url(r'^api-discussions/', include(discussion_router.urls)),
    url(r'^api-blog/', include(blog_router.urls)),
    url(r'^api-maps/', include(map_router.urls)),
    url(r'^api-userspace/', include(user_router.urls)),
    url(r'^api-core/', include(core_router.urls)),
    url(r'^api-gallery/', include(gallery_router.urls)),
    url(r'^api-notifications/', include(notification_router.urls)),
    url(r'^api-activities/', include(activity_router.urls)),
    url(r'^api-hitcounter/', include(hitcounter_router.urls)),
    url(r'^api-comments/', include(comment_router.urls)),
    url(r'^api-polls/', include(poll_router.urls)),
    url(r'^api-bless/', include(bless_router.urls)),
    url(r'^api-projects/', include(project_router.urls)),
    url(r'^api-mapvotes/', include(mapvotes_router.urls)),
)

from civmail.views import ContactEmailView, InviteFriendsView
urlpatterns += patterns('',
    url(r'^contact/', ContactEmailView.as_view(), name="contact"),
    url(r'^invite-friends/', InviteFriendsView.as_view(), name="invite_friends"),
)

from places_core.views import set_language
urlpatterns += patterns('',
    url(r'^', include('hitcounter.urls')),
    url(r'^ranking/(?P<code>[a-zA-Z]{2})/regions/', RegionRankingView.as_view(), name="ranking-regions"),
    url(r'^ranking/(?P<code>[a-zA-Z]{2})/locations/', LocationRankingView.as_view(), name="ranking-locations"),
    url(r'^ranking/(?P<code>[a-zA-Z]{2})/', CityRankingView.as_view(), name="ranking-cities"),
    url(r'^ranking/', CountryRankingView.as_view(), name="ranking-countries"),
    url(r'^activities/', include('activities.urls', namespace="activities")),
    url(r'^tracker/', include('user_tracker.urls', namespace="tracker")),
    url(r'^guides/', include('guides.urls', namespace="guides")),
    url(r'^organizations/', include('organizations.urls', namespace="organizations")),
    url(r'^simpleblog/', include('simpleblog.urls', namespace="simpleblog")),
    # user account
    url(r'^user/', include('userspace.urls', namespace='user')),
    url(r'^users/', include('userspace.urls', namespace='user')),
    url(r'^bookmarks/', include('bookmarks.urls')),
    # Email app
    url(r'^civmail/', include('civmail.urls', namespace='civmail')),
    url(r'^civmail-admin/', include(civmail_admin_site.urls)),
    # Maps
    url(r'^maps/', include('maps.urls', namespace='maps')),
    # blog
    url(r'^news/', include('blog.urls', namespace='blog')),
    # ideas
    url(r'^ideas/', include('ideas.urls', namespace='ideas')),
    # django-activity-stream
    url(r'^activity/', UserActivityView.as_view()),
    # social auth
    url('', include('social.apps.django_app.urls', namespace='social')),
    # django-discussions (e.g. user messages)
    # disabled because of lack South integrity
    #url('^messages/', include('discussions.urls', namespace='messages')),
    # Basic project views - the rest is within locations
    url('^projects/', include('projects.urls', namespace='projects')),
    # Discussions (e.g. forum)
    url('^discussion/', include('topics.urls', namespace='discussion')),
    # comments
    url('^comments/', include('comments.urls', namespace='comments')),
    # admin panel
    url(r'^fuck-off-i-am-awesome/', include(admin.site.urls)),
    # Abuse reports (static)
    url(r'^report/', include('places_core.urls', namespace='reports')),
    # User media
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    # Polls app
    url(r'^polls/', include('polls.urls', namespace='polls')),
    # Static pages
    url(r'^pages/', include('staticpages.urls', namespace='pages')),
    # media
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    # REST server
    url(r'^rest/', include(router.urls, namespace='rest')),
    # Haystack - search engine
    url(r'^search/', include('haystack.urls', namespace='search')),
    # django-messages: messages between users
    url(r'^messages/', include('postman.urls')),
    # Language support
    url(r'^i18n/setlang', set_language, name='set_language'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    # For robots - indexers :)
    url(r'^robots.txt$', FileServeView.as_view(filename='robots.txt')),
    # Captcha
    url(r'^captcha/', include('captcha.urls')),
    # Static Pages
    # Definition of static pages go here, you can add new ones by
    # copy-paste method.
    url(r'^home/', PageView.as_view(page='home')),
    url(r'^home-b/', PageView.as_view(page='home-b')),
    url(r'^home-c/', PageView.as_view(page='home-c')),
    url(r'^home-d/', PageView.as_view(page='home-d')),
    url(r'^home-e/', PageView.as_view(page='home-e')),
    url(r'^home-f/', PageView.as_view(page='home-f')),
    url(r'^home-g/', PageView.as_view(page='home-g')),
    url(r'^home-h/', PageView.as_view(page='home-h')),
    url(r'^home-i/', PageView.as_view(page='home-i')),
    url(r'^home-j/', PageView.as_view(page='home-j')),

    #url(r'^about/', PageView.as_view(page='about')),
    #url(r'^privacy/', PageView.as_view(page='privacy')),
    #url(r'^terms/', PageView.as_view(page='terms')),
    #url(r'^cookies/', PageView.as_view(page='cookies')),
    #url(r'^contact/', PageView.as_view(page='contact')),
    #url(r'^jobs/', PageView.as_view(page='jobs')),
    #url(r'^press/', PageView.as_view(page='press')),
    #url(r'^mission/', PageView.as_view(page='mission')),
    #url(r'^team/', PageView.as_view(page='team')),
    #url(r'^values/', PageView.as_view(page='values')),
    #url(r'^creed/', PageView.as_view(page='creed')),
    #url(r'^support/', PageView.as_view(page='support')),
    url(r'^feature/', PageView.as_view(page='feature')),

    # Etherpad - live collaboration tool
    url(r'^', include('etherpad.urls')),

    # Notifications for users - mainly views for testing.
    url(r'^', include('notifications.urls')),

    #url(r'^$', HomeView.as_view(template_name='staticpages/pages/home-e.html')),
    url(r'^$', RegisterFormView.as_view()),

maps/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.gis.db import models
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.db.models import get_model
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from .managers import MapPointerManager


class BaseAbstractMapPointer(models.Model):
    """
    An abstract base class that any custom pointer models probably should subclass.
    """
    # Content-object field
    content_type = models.ForeignKey(ContentType,
            verbose_name=_('content type'),
            related_name="content_type_set_for_%(class)s")
    object_pk = models.TextField(_('object ID'))
    content_object = generic.GenericForeignKey(ct_field="content_type", fk_field="object_pk")

    class Meta:
        abstract = True


@python_2_unicode_compatible
class MapPointer(BaseAbstractMapPointer):
    """ Final MapPointer class. """
    latitude = models.FloatField()
    longitude = models.FloatField()
    location = models.ForeignKey('locations.Location', null=True, blank=True)

    objects = MapPointerManager()

    def __str__(self):
        return "{},{}".format(self.latitude, self.longitude)

    class Meta:
        unique_together = ('latitude', 'longitude',
                           'object_pk', 'content_type', )

maps/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
import models


class MapPointerForm(forms.ModelForm):
    """
    Custom pointer form for testing purposes. This form
    is rendered as static page instead of AJAXy form.
    """
    content_type = forms.ModelChoiceField(
        label = _("Content type"),
        queryset = ContentType.objects.all(),
        widget = forms.Select(attrs={'class': 'form-control'})
    )
    object_pk = forms.IntegerField(
        label = _("Object id"),
        widget = forms.NumberInput(attrs={'class': 'form-control'})
    )
    latitude = forms.FloatField(widget=forms.HiddenInput())
    longitude = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = models.MapPointer
        fields = ('content_type', 'object_pk', 'latitude', 'longitude',)


class AjaxPointerForm(forms.ModelForm):
    """
    This form is displayed in modal window when user add map pointer
    for selected content element. It contains only hidden elements
    to get JavaScript handle everything else.
    """
    content_type = forms.ModelChoiceField(
        queryset = ContentType.objects.all(),
        widget   = forms.HiddenInput()
    )
    object_pk = forms.IntegerField(widget = forms.HiddenInput())
    latitude = forms.FloatField(widget=forms.HiddenInput())
    longitude = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = models.MapPointer
        fields = ('content_type', 'object_pk', 'latitude', 'longitude',)

maps/templates/maps/index.html
{% load staticfiles i18n civil_tags %}
{% include 'places_core/header.html' %}

{% block meta %}<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="CivilHub">
<meta name="twitter:title" content="{{ title }}">
<meta property="og:title" content="{{ title }}"/>
<meta property="og:image" content="https://civilhub.org/media/filer_public/2f/d2/2fd2fa32-a8a9-4528-9d9e-9ef5f2d88f74/pl_slide_8.jpg"/>
<meta property="og:site_name" content="CivilHub"/>
<meta property="og:url" content="https://civilhub.org/maps/" />
<meta property="og:description" content="{% trans "Jump into the map and see what is happening in your place." %}"/>
<meta name="keywords" content="{{ title }}">{% endblock %}


{% include 'places_core/script-templates.html' %}

<link rel="stylesheet" href="{% static 'places_core/includes/leaflet/MarkerCluster.css' %}">
<link rel="stylesheet" href="{% static 'places_core/includes/leaflet/MarkerCluster.Default.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'places_core/css/staticpages/maps.min.css' %}">

<script type="text/javascript" src="{% url 'django.views.i18n.javascript_catalog' %}"></script>
<script>
(function () {

"use strict";

window.STATIC_URL = "{% static 'places_core' %}";

window.MAP_STATIC_URL = "{% static 'maps' %}";

window.CONTENT_TYPES = {
{% for type in content_types %}
  {{ type.pk }}: {
    content_type: "{{ type.pk }}",
    app_label: "{{ type.app_label }}",
    model: "{{ type.model }}"
  },
{% endfor %}
};

window.CIVILAPP = {
  {% if active_marker %}
  current: {
    latitude: ("{{ active_marker.latitude }}").replace(',', '.'),
    longitude: ("{{ active_marker.longitude }}").replace(',', '.'),
    object_pk: "{{ active_marker.content_object.pk }}",
    content_type: "{{ active_marker.content_type.pk }}"
  },{% endif %}
  position: {
    lat: ("{{ position.lat }}").replace(',', '.'),
    lng: ("{{ position.lng }}").replace(',', '.')
  },
  icons: { {% for type in content_types %}
    {% if type.model in icons %}'{{ type.pk }}': {
      iconUrl: "{% static 'maps' %}/icons/marker-{{ type.model }}.png",
      iconRetinaUrl: "{% static 'maps' %}/icons/marker-{{ type.model }}@2x.png",
      iconSize: [23, 27]
    },{% endif %}
  {% endfor %} }
};

})();
</script>
<script src="{% static 'places_core' %}/includes/require/require.js"></script>
<script src="{% static 'places_core' %}/js/{% js_path %}/map-main.js"></script>
<script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.5/mapbox.js'></script>
</head>

<body>

{% include 'places_core/navigation.html' %}

<div id="map-options-toggle">
  <div id="map-filter-toggle" href="#" title="{% trans "Filters Map" %}">
    <div class="sprite-icon"><span class="ch-icon ch-subspaces"></span> {% trans "Filters Map" %}</div>
    <div class="angle-icon-toggle"><span class="fa fa-angle-down"></span></div>
  </div>
</div>

<div id="map-options-panel">
  <div class="content">
  {% trans "Choose place" %}
    <nav id="country-nav-panel" role="navigation" class="civ-map-controller">
      <form id="country-nav-form">
        <input type="text" id="select-location-field" placeholder="{% trans "Search" %}" />
      </form>
    </nav>
  </div>
  <div class="controls-divider"></div>
  <div class="content">
    {% trans "Show" %}
    <nav class="civ-map-controller" role="navigation">
      <ul>
        <li><input type="checkbox" data-target="locations.location" class="map-filter-toggle" checked="checked" /><img src="{% static 'maps/icons/marker-location.png' %}" /> {% trans "Places" %}</li>
        <li><input type="checkbox" data-target="ideas.idea" class="map-filter-toggle" checked="checked" /><img src="{% static 'maps/icons/marker-idea.png' %}" /> {% trans "Ideas" %}</li>
        <li><input type="checkbox" data-target="polls.poll" class="map-filter-toggle" checked="checked" /><img src="{% static 'maps/icons/marker-poll.png' %}" /> {% trans "Polls" %}</li>
        <li><input type="checkbox" data-target="topics.discussion" class="map-filter-toggle" checked="checked" /><img src="{% static 'maps/icons/marker-discussion.png' %}" /> {% trans "Discussions" %}</li>
        <li><input type="checkbox" data-target="blog.news" class="map-filter-toggle" checked="checked" /><img src="{% static 'maps/icons/marker-news.png' %}" /> {% trans "News" %}</li>
        <li><input type="checkbox" data-target="projects.socialproject" class="map-filter-toggle" checked="checked" /> <img src="{% static 'maps/icons/marker-socialproject.png' %}" /> {% trans "Projects" %}</li>
      </ul>
    </nav>
  </div>
</div>

<div id="main-map"><div class="chSpinBox"><img src="{% static 'maps/images/logo.svg' %}" alt="CivilHub spin" class="fa-chSpin chSpin"><!-- <span class="fa fa-spin fa-circle-o-notch">&nbsp;</span> --></div></div>

</body>
</html>
{% include 'places_core/script-templates/flash-msg-tpl.html' %}

maps/templates/maps/minimap.html
{% load i18n staticfiles %}<script>
(function () {
  "use strict";
  var app = app || {markers:[]};
  {% for m in MARKERS %}app.markers.push({
    lat: '{{ m.latitude }}',
    lng: '{{ m.longitude }}',
    pk: '{{ m.pk }}'
  });{% endfor %}
  app.staticUrl = "{% static 'places_core' %}";
  {% if location %}app.currentLocationId = {{ location.pk }};{% endif %}
  // Export to global because of legacy scripts
  window.mapApp = app;
})();
</script>
<div id="minimap-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">{% trans "Close" %}</span></button>
        <h4 class="modal-title">{% trans "Minimap" %}</h4>
      </div>
      <div class="modal-body"><div id="minimap"></div></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-cancelBig" data-dismiss="modal">{% trans "Close" %}</button>
        <button type="submit" class="btn btn-primary btn-saveBig">{% trans "Save" %}</button>
      </div>
    </div>
  </div>
</div>

maps/templates/maps/pointer-form.html
{% extends 'places_core/base.html' %}
{% load staticfiles %}{% load i18n %}

{% block content %}
<form role="form" method="post" action="">
    {% csrf_token %}
    {{ form }}
    <div class="form-group">
        <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    </div>
</form>
{% endblock %}

{% block footer_scripts %}
<script src="{% static 'maps/js/jquery.mapinput.js' %}"></script>
<script>
(function ($) {
    "use strict";
    $('#id_latitude').before('<div class="map"></div>');
    $('#id_latitude, #id_longitude').css('display', 'none');
    $('#map').mapinput({
        latField: '#id_latitude',
        lngField: '#id_longitude',
        width: 640,
        height: 480
    });
})(jQuery);
</script>
{% endblock %}

maps/templates/maps/pointer-modal-form.html
{% load staticfiles i18n %}

{% comment %}
    Add point on map form template. The form is filled in automatically
    based on the chosen content.
{% endcomment %}

<script type="text/template" id="map-marker-form-template">
<div class="modal fade" id="pointer-form">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">{% trans "Create map marker" %}</h4>
            </div>
            <div class="modal-body">
                <form role="form" method="post" action="#">
                    {{ marker_form }}
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                <button type="submit" class="btn btn-primary submit-btn">{% trans "Save" %}</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
</script>